### ISSUE TITLE
Crashing with custom test if the test failed

### ISSUE THREAD

**Issue by erkac** [f5devcentral/f5-waf-tester#7]
Hi team,

I have an API based WAF policy in my AWAF. I have created a new test to see if the `/` is blocked by WAF policy. Here is the test.
```
  {
    "id": "100000025",
    "name": "Path Traversal to root",
    "attack_type": "Path Traversal",
    "system": "All systems",
    "CVE": "",
    "vectors": [
      {
        "applies_to": "request",
        "payload": "GET / HTTP/1.1\r\nHost: {hostname}\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: {user_agent}\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-US,en;q=0.9\r\n\r\n",
        "expected_result": {
          "type": "evasion",
          "value": "Illegal URL"
        }
      }
    ]
  }
```

If the `/` is blocked in the WAF policy the result is ok:
```
    "100000025": {
      "CVE": "", 
      "attack_type": "Path Traversal", 
      "name": "Path Traversal to root", 
      "results": {
        "request": {
          "expected_result": {
            "type": "evasion", 
            "value": "Illegal URL"
          }, 
          "pass": true, 
          "reason": "", 
          "support_id": "11280365323838031349"
        }
      }, 
      "system": "All systems"
    }
  }, 
  "summary": {
    "fail": 0, 
    "pass": 49
  }
}
```

Event Log - blocked:
<img width="1583" alt="waf-blocked" src="https://user-images.githubusercontent.com/5064350/95727323-49e1a480-0c7a-11eb-9a2b-791c80fa1a86.png">

...but if I allow `/` in the WAF policy the test is actually marked as failed but the f5-waf-tester crashes and generate this output:
```
12-10-20 08:54:22 INFO Test 100000025/request failed
12-10-20 08:54:22 INFO Test 100000013/url pass
12-10-20 08:54:22 INFO Test 100000012/parameter pass
12-10-20 08:54:22 INFO Test 100000014/url pass
12-10-20 08:54:22 INFO Test 100000009/url pass
12-10-20 08:54:22 INFO Test 100000023/parameter pass
12-10-20 08:54:22 INFO Test 100000015/url pass
12-10-20 08:54:22 INFO Test 100000014/parameter pass
Traceback (most recent call last):
  File "/usr/local/bin/f5-waf-tester", line 11, in <module>
    load_entry_point('f5-waf-tester==0.1.1b0', 'console_scripts', 'f5-waf-tester')()
  File "/usr/local/lib/python2.7/dist-packages/f5_waf_tester/__init__.py", line 503, in main
    ).start(report_path=sys_args['report']))
  File "/usr/local/lib/python2.7/dist-packages/f5_waf_tester/__init__.py", line 390, in start
    self.report = self.get_report()
  File "/usr/local/lib/python2.7/dist-packages/f5_waf_tester/__init__.py", line 276, in get_report
    global_reasons = self._get_global_reasons()
  File "/usr/local/lib/python2.7/dist-packages/f5_waf_tester/__init__.py", line 254, in _get_global_reasons
    )["items"][0]
IndexError: list index out of range
```

Event Log - passed:
<img width="1587" alt="waf-passed" src="https://user-images.githubusercontent.com/5064350/95727084-071fcc80-0c7a-11eb-9957-5046d785a14e.png">

Thank you.

Regards,
Lubos Klokner

**Comment by realgam3** [comment]
It fixed on version 1.0 we are working on the release
